구조 변경 및 세팅 파일 조정
jiks-dev/service-github pull request #1
Opened 2021-08-24 11:23 UTC by ldh1428a

2021-08-24 12:22 UTC, prtrans23 commented on GitHubService/GitHubService.Domain/AggregatesModel/OrganizationAggregates/Organization.cs
> +    }
TODO 로 Organization 클래스가 어떤 역할을 할 것인지 간단하게 적어주세요~

2021-08-24 12:26 UTC, prtrans23 requested changes
Check Comments 
- GitHubService.API
- GithubService.API 
가 폴더에 중복으로 있는것으로 보임. 삭제 요청드립니다.

2021-08-24 12:26 UTC, prtrans23 commented on GitHubService/GitHubService.Domain/AggregatesModel/OrganizationAggregates/Organization.cs
> +    public class Organization
TODO 로 Organization 클래스가 어떤 역할을 할 것인지 간단하게 적어주세요~

2021-08-24 12:26 UTC, prtrans23 commented on GitHubService/GitHubService.Domain/GitHubService.Domain.csproj
> +    <TargetFramework>netcoreapp3.1</TargetFramework>
Net 5 로 업그레이드 합시다

2021-08-24 12:26 UTC, prtrans23 commented on GitHubService/GithubSerivce.API/Controllers/WeatherForecastController.cs
> +    public class WeatherForecastController : ControllerBase
사용하지 않을 Class 제거

2021-08-24 12:26 UTC, prtrans23 commented on GitHubService/GithubSerivce.API/WeatherForecast.cs
> +    public class WeatherForecast
사용하지 않는 클래스 제거

2021-08-30 00:56 UTC, ldh1428a commented
해당 PR은 초기 파일 변경 건으로 잘못 요청 되어 Close 처리합니다.

2021-08-30 00:56 UTC, closed without merging